# Site
repository: subbak2/subbak2.github.io
# favicon: images/favicon.ico

# Personal info
name: 박경섭
title: DBA, 소프트웨어 개발자
email: subbak2@gmail.com
website: https://subbak2.tistory.com

# Social links
# twitter_username: jojoldu
github_username: subbak2
# dribbble_username: jekyll
# facebook_username: jojoldu
# flickr_username: jekyll
linkedin_username: subbak2
# pinterest_username: jekyll
youtube_username: '@subcoding7036'

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Oracle DBMS / Java & Spring 기반의 5년차 SW 엔지니어<br/><br/>
  삼성카드 시스템을 운영하며, 신규 시스템 구축 지원을 했습니다.<br/>
  개인이 하고 싶은 일 보다 **회사와 팀에 도움이 되는** 개발을 중요하게 생각합니다.<br/><br/>
  Oracle DBMS를 기반으로 MariaDB, PostgreSQL(EPAS)를 경험했고, <br/>
  Java Spring을 기반으로 JSP, xplatform, Vus.js, Nuxt.js를 경험했고, <br/>
  On-premise, AWS, SCP 등의 인프라 위에서 Unix, Linux를 경험했습니다.<br/><br/>
  현재는 **DBA**로 SQL튜닝, 스토리지 최적화, 데이터 아키텍처 설계, 모니터링 개발을 주요 업무로 하고 있습니다.<br/>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
